### ISSUE TITLE
Update database/storage strategy

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#117]
## Do you want to request a *feature* or report a *bug*?
Feature
## What is the current behavior?
At the moment an old version of prisma(graphcool) is being used to save data and interact with Apollo. All of the above is out of and needs to be update.

## What is the expected behavior?
- Update Apollo
- Update Prisma or move to another solution
- Identify schema for the following
  - ContributorBreadcrumbs (model to store key repo info) 
  - Saved Repos 
    - Save notes for saved repos (Wiki - should these be public?)

**Comment by sgrove** [comment]
Having open-sauced be completely backed by GitHub would be pretty cool, and make the app itself pretty much entirely stateless. I see two ways to actually store per-user data:

1. gists: You can create a gist-per-user with some json in there to keep the state of the user.
Pros: Flexible, you can store whatever JSON you want.
Cons:
- Migrations will become a never-ending nightmare. You'll never know if you're safe to change the data structures in your code because there might be some gist out there you forgot about
- If a user has more than one tab open and makes a change that's saved to the gist, that change won't be reflected in the other tabs. Then if they go to the other tab and make some *different* changes and save those, the *all* the first set of changes will be lost. It may not matter for a *tiny, tiny* app, but anything with more than one dev/user this can be pretty bad.

2. Issues on a repository: When a user first signs up, create a repository for them specifically for tracking open-sauced issues. Create an issue for each watched-issue on other repositories that the user wants to track, and store their notes in the body of the issue. Attach labels to the issue for filtering later ("js", "machine-learning", "free-time", "interview", etc. - let me filter the issues by the tags I assign to the issue).
Cons: You're much more limited in the data you can store, and you have to make it somehow fit into "issues-like" data structure. A bit irksome, but not too bad.
Pros:
- The data structures are baked into GitHub's API, so GraphQL will tell you if anything breaks. Individual changes to issues will still cause concurrency issues like above, bu the granularity is now per-issue.
- You can pretty easily fit a robust UI for this project into the structure of an issue, using title, body, comments, labels, assigness, milestones, etc. Just repurposes them for your own use.
- The user will now have an alternative view of the data - through the GitHub UI! They're not necessarily locked into open-sauce's view of things, because they have this open, public, familiar view with full-api access they can get to any time.

Obviously I'm in favor of #2, but I think it's pretty cool that with either you shouldn't need a backend at all for this! All the logic is client-side, with permissions enforced via GitHub's auth.

**Comment by sgrove** [comment]
If you go with #2, I wrote up all of the queries/mutations you'll probably need: https://serve.onegraph.com/short/BNK4Q5

You can use the code exporter to automatically get functions to do all of them in a copy/paste way in the app itself (just use the JavaScript/fetch option without `async`).

**Comment by bdougie** [comment]
@sgrove thanks for writing all this our and event providing the mutations and queries. I really like the idea of Open Sauced being an extension on top of GitHub and not a replacement. 

I am definitely pro path 2.

**Comment by bdougie** [comment]
This is now working and function thanks to #182
