### ISSUE TITLE
Use Github stars for "tracked repos"

### ISSUE THREAD

**Issue by rolfea** [bdougie/open-sauced#32]
**- Do you want to request a *feature* or report a *bug*?**
**Feature**  
Instead of manually adding GitHub repos that a user is interested in following, Open Sauced could instead utilize a users' starred repos to populate their tracked repo list.  
  
This would likely need to be prefaced with Github authentication.

**Comment by bdougie** [comment]
Trying to think through this and I personally have hundreds of starred repos. I would need some sort of filtering or search to make this feature useful. I am not convinced this is the best route since it would also encourage unstarring repos. 

Perhaps adding a searchable or paginated list of starred Repos to the New Repo form would be ideal.

**Comment by bdougie** [comment]
#153 now tracks repos you have contributed to. This is a temporary fix. The plan now will be to present the user a way to create an open-sauced-goals repo to store notes and track repos. Outlined in https://github.com/bdougie/open-sauced/issues/117#issuecomment-526795800
