### ISSUE TITLE
Show full name and avatar in the navbar

### ISSUE THREAD

**Issue by yg** [bdougie/open-sauced#539]
### Describe the solution you'd like

Show full name in the navbar, if there is no name we will fall back to the username (login)

We can also show user avatar from GitHub

### Additional context

![Screenshot](https://user-images.githubusercontent.com/61746440/82742192-5c654b00-9d78-11ea-8fbd-584c83be6de4.png)

**We need to enable `avatar` and `name` property in GitHub API @ Onegraph**

If ok, I'm ready to work on this!

**Comment by bdougie** [comment]
This is lower priority while the the home page and other various bugs exist. 

But this is also trivial to update to add. Feel feee to work on it, but rather than have the name at all, would actually prefer just the avatar in the nav.

The apiGraphQL.js can get updated to add the avatar to the data being fetched.

**Comment by yg** [comment]
.take
